### ISSUE TITLE
Compiling with `-panics:on` fails

### ISSUE THREAD

**Issue by SolitudeSF** [haxscramper/hpprint#1]
`pprint 1` fails with `hmisc-0.9.13/hmisc/algo/hstring_algo.nim(93, 6) Error: 'len' can have side effects`

**Comment by haxscramper** [comment]
Should be fixed on latest version - I corrected version requirements, so it should update to include fixes to `hmisc`

**Comment by SolitudeSF** [comment]
~~now fails with `hnimast-0.3.10/hnimast.nim(141, 6) Error: 'expectKind' can have side effects`~~
works after updating hnimast manually
